name: Plugin PHPUnit Tests

on: 
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    #Fast MySQL Action (instead of Docker)
    - uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: '5.7'
        mysql database: 'wordpress_test'
        mysql user: 'root'
        mysql password: ''

    steps:
    - uses: actions/checkout@v4

    - name: Cache Composer files
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Cache WP Test Suite
      uses: actions/cache@v4
      with:
        path: |
          /tmp/wordpress-tests-lib
          /tmp/wordpress
        key: ${{ runner.os }}-wp-tests-${{ hashFiles('bin/install-wp-tests.sh') }}
        restore-keys: ${{ runner.os }}-wp-tests-

    - uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, mysql, mysqli
        tools: composer

    - name: Install WP Test Suite
      run: bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest

    - name: Install Composer deps
      run: composer install --no-interaction --prefer-dist

    - name: Run PHPUnit
      run: vendor/bin/phpunit
