name: Plugin PHPUnit Tests

on: 
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        #image: mysql:5.7
        image: mariadb:10.6
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: >-
          --health-cmd="echo ok" 
          --health-interval=1s 
          --health-timeout=1s 
          --health-retries=1
      #--health-cmd="mysqladmin ping -h localhost" 
      #--health-interval=10s 
      #--health-timeout=5s 
      #--health-retries=10

    steps:
    - uses: actions/checkout@v4

    # ------------------------
    # Cache Composer directory
    # ------------------------
    - name: Cache Composer files
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    # ------------------------
    # Cache WordPress test suite
    # ------------------------
    - name: Cache WP Test Suite
      uses: actions/cache@v4
      with:
        #path: /tmp/wordpress-tests-lib
        path: |
            /tmp/wordpress-tests-lib
            /tmp/wordpress
        key: ${{ runner.os }}-wp-tests-${{ hashFiles('bin/install-wp-tests.sh') }}
        restore-keys: |
          ${{ runner.os }}-wp-tests-

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, mysql, mysqli
        tools: composer

    - name: Install Subversion (svn)
      run: |
        sudo apt-get update
        sudo apt-get install -y subversion

    - name: Reset test DB
      run: mysql -h127.0.0.1 -uroot -p -e "DROP DATABASE IF EXISTS wordpress_test;"

    - name: Install WP Test Suite (runs only if cache not restored)
      run: bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest
      # prevents rerunning if cached
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Install Composer deps
      run: composer install --no-interaction --prefer-dist

    - name: Run PHPUnit
      run: vendor/bin/phpunit
